fail_fast: true
repos:
-   repo: https://github.com/timothycrosley/isort
    rev: 'develop'  # Use the revision sha / tag you want to point at
    hooks:
    -   id: isort
        args: [--profile=django]
-   repo: https://gitlab.com/pycqa/flake8
    rev: ''  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        exclude: (migrations/|settings|manage)
        additional_dependencies: [
            pep8,
            pep8-naming,
            flake8-polyfill,
            flake8-string-format,
            flake8-rst-docstrings,
            flake8-quotes,
            flake8-print,
            flake8-pep3101,
            flake8-logging-format,
            flake8-executable,
            flake8-eradicate,
            flake8-docstrings,
            flake8-django,
            flake8-debugger,
            flake8-comprehensions,
            flake8-commas,
            flake8-coding,
            flake8-builtins, 
            flake8-bugbear,
            flake8-broken-line,
            flake8-bandit, 
        ]
