# Generated by Django 2.2.4 on 2019-08-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20190812_0608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='task_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='task_priority',
            new_name='priority',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='task_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='task_name',
            new_name='title',
        ),
    ]
